# log config
log_config:
  level: error                 # The log level
  filename: ../log/ca.log      # Log access path
  max_size: 1                  # The maximum size of each log file saved
  max_age: 30                  # The maximum number of days the file is kept
  max_backups: 5               # The maximum number of backups the log file can hold

# db config
db_config:
  user: root
  password: 123456
  ip: 192.168.12.145
  port: 13306
  dbname: chainmaker_ca

# Base config
base_config:
  ca_type: double_root                               # Boot mode: sign/tls/double_root/solo_root 
  expire_year: 2                                     # Valid life of issue
  hash_type: SHA256                                  # using the hash type SHA256/SHA3_256/SM3 is currently supported
  key_type: ECC_NISTP256                             # Using key types ECC_NISTP256/SM2 is currently supported
  can_issue_ca: true                                 # Multistage CA switch
  provide_service_for: [org1,org2,org7]              # A list of organizations to which services are provide
  key_encrypt: false                                 # Whether the key is stored in encryption

# Root CA config
root_config:
  cert:
  #   -
  #     cert_type: sign
  #     cert_path: ../crypto-config/rootCA/root.crt             # Access path of root certificate
  #     private_key_path: ../crypto-config/rootCA/root.key      # Access path of root private key
  #     private_key_pwd: wx123
    -
      cert_type: tls
      cert_path: ../crypto-config/rootCA/tls/root-tls.crt            
      private_key_path: ../crypto-config/rootCA/tls/root-tls.key      
      private_key_pwd: wx123
    -
      cert_type: sign
      cert_path: ../crypto-config/rootCA/sign/root-sign.crt               
      private_key_path: ../crypto-config/rootCA/sign/root-sign.key       
      private_key_pwd: wx123

  csr:
    CN: root.org-wx                   # The CommonName field of X509 is equivalent to the user ID
    O: org-wx                         # The Orgnization field of X509 is equivalent to an organization ID
    OU: root                          # The OrgnizationUnit field of X509 is equivalent to the user type
    country: CN                       # The Country field for X509
    locality: Beijing                 # The Locality field for X509
    province: Beijing                 # The province field for X509  

# Intermediate config
Intermediate_config:                 # Optional, fill in the intermediate CA that will generate the configuration when the service is started. Multiple intermediate CA configurations can be filled
  -
    csr:
      CN: ca.org8
      O: org1
      OU: ca
      country: CN
      locality: Beijing
      province: Beijing
  -
    csr:
      CN: ca.org9
      O: org2
      OU: ca
      country: CN
      locality: Beijing
      province: Beijing
    private_key_pwd: wx123
  -
    csr:
      CN: ca.org7
      O: org7
      OU: ca
      country: CN
      locality: Beijing
      province: Beijing
    private_key_pwd: wx123