apiVersion: apps/v1
kind: Deployment
metadata:
  #名字规范 模块名-deploy-模块内微服务名
  name: tbaas-deploy-certwx
  #命名空间规范 模块名
  namespace: tbaas
  # these labels can be applied automatically
  # from the labels in the pod template if not set
spec:
  # 容器运行个数
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1      #滚动升级时会先启动1个pod
      maxUnavailable: 1 #滚动升级时允许的最大Unavailable的pod个数
  # selector can be applied automatically
  # from the labels in the pod template if not set
  selector:
    matchLabels:
        module: tbaas
        app: certwx
  template:
    metadata:
      labels:
        #规范： module为模块名 app为微服务名 tier 为角色 请根据实际填写，比如 mysql主从的monitor slave等
        module: tbaas
        app: certwx
    spec:
  #    nodeSelector:
  #      node_name: 10.0.0.10   #预留用于区分管控节点和区块链节点
      nodeSelector:
        kubernetes.io/hostname: 10.0.0.10
      containers:
      #规范： 模块名-微服务名-自定义名-container
      - name: tbaas-certwx-container
        image: docker.oa.com:5000/tbaas/tbaas-cert-wx:v1.0.0
        securityContext:
          capabilities:
           add: ["SYS_ADMIN"]
        volumeMounts:
        #规范：volume-开头，后面根据用途填写
        - name: volume-certwx-log
          mountPath: /chainmaker-ca-backend/log
        - name: volume-certwx-conf
          mountPath: /chainmaker-ca-backend/conf/
#        - name: volume-certs-storage
#          mountPath: /data/release/ca
        ports:
        - containerPort: 8090
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        readinessProbe: #kubernetes认为该pod是启动成功的
          tcpSocket:
            port: 8090
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5
        livenessProbe: #kubernetes认为该pod是存活的,不存活则需要重启
          tcpSocket:
            port: 8090
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      volumes:
        - name: volume-certwx-log
          hostPath:
            path: /data/k8s/log/certwxlog
        - name: volume-certwx-conf
          configMap:
            name: tbaas.cm.certwx
#        - name: volume-certs-storage
#          hostPath:
#            path: /data/release/syndir/certwx
          #persistentVolumeClaim:
          #  claimName: certs
