# log config
log_config:
  level: error
  filename: ../log/ca.log
  max_size: 1
  max_age: 30
  max_backups: 5

# db config
db_config:
  user: root
  password: 123456
  ip: 192.168.12.129
  port: 3306
  dbname: certs

# CA config
is_generate_rootca: true
ca_type: double                        #sign/tls/double/solo
expire_year: 2
hash_type: SHA256 
key_type: ECC_NISTP256
is_encrypted_privatekey: true
crl_next_time: 24h

# Root CA config
root_config:
  org_id: wx-root                  
  country: CN                  
  locality: Beijing               
  province: Beijing     
  privatekey_pwd: wx-123
  is_generate_keypair: true
  cert_path: ../crypto-config/RootCA/root.crt
  privatekey_path: ../crypto-config/RootCA/root.key

#Root double CA path
rootpath_double:
    tls_cert_path: ../crypto-config/RootCA/tls/root-tls.crt
    tls_privatekey_path: ../crypto-config/RootCA/tls/root-tls.key
    sign_cert_path: ../crypto-config/RootCA/sign/root-sign.crt
    sign_privatekey_path: ../crypto-config/RootCA/sign/root-sign.crt        
