# 日志配置
log_config:
  level: debug
  filename: ./log/default.log
  max_size: 1
  max_age: 30
  max_backups: 5

  # 数据库配置
db_config:
  user: root
  password: 123456
  ip: 127.0.0.1
  port: 3306
  dbname: chainmaker

  # 根用户的初始化配置
root_config:
  private_key_type: AES
  private_key_path: ./crypto-config/root
  private_key_name: root.key
  cert_path: ./crypto-config/root
  cert_name: root.crt
  hash_type: SHA256
  expire_year: 1                     
  country:                               
  locality:                                
  province:                              
  O:                                      
  OU:                             
  CN:        

# 中间CA配置文件
intermediaries_config:
  csr_path:
  csr_name: 
  country:                                        
  locality:                                         
  province:                                      
  O:                                                     
  OU:                                                  
  CN:                                                  
  cert_path:
  cert_name:
  expire_year: