# 日志配置
log_config:
  level: debug
  filename: ./log/default.log
  max_size: 1
  max_age: 30
  max_backups: 5

  # 数据库配置
db_config:
  user: root
  password: 123456
  ip: 127.0.0.1
  port: 3306
  dbname: chainmaker

#是否初始化根CA
is_init_root_ca: false
#密钥加密类型
private_key_type: SM2
#哈希类型
hash_type: SHA256
#签发证书的过期时间
issure_expiration_time: 1

  # 根CA的初始化配置
root_config:
  username: root
  private_key_pwd: wx123
  private_key_path: ./crypto-config/root/root.key
  cert_path: ./crypto-config/root
  cert_name: root.crt
  expire_year: 1                     
  country: China                   
  locality: Beijing               
  province: Beijing                      
  O: wx                       
  OU: wx.chainmaker                 
  CN: ca.wx.chainmaker

# 中间CA配置文件
intermediaries_config:
  username: admin
  private_key_pwd: 123456
  private_key_path: ./crypto-config/intermediaries/intermediaries.key
  country: China                               
  locality: Beijing                                   
  province: Beijing                              
  O: chainmaker                                              
  OU: wx.chainmaker                                         
  CN: ca.wx.chainmaker                                     
  cert_path: ./crypto-config/intermediaries
  cert_name: ./intermediaries.crt
  expire_year: 1